import streamlit as st
import sys
import os
import json
from datetime import datetime
import pandas as pd
import base64
from fpdf import FPDF
import re



import streamlit as st
import json
import re
from fpdf import FPDF
import os

def clean_text(text):
    # Replace non-ASCII characters with a placeholder (e.g., space)
    return ''.join(char if ord(char) < 128 else ' ' for char in text)



def create_pdf(occasion, menu):
    """Create a PDF for the menu"""
    pdf = FPDF()
    pdf.add_page()
    occasion = occasion.replace('•', '*')
    occasion = clean_text(occasion)

    # Add logo/header
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, "Master Chef AI", 0, 1, 'C')
    pdf.set_font('Arial', 'I', 12)
    pdf.cell(0, 10, f"Menu for: {occasion}", 0, 1, 'C')
    pdf.line(10, 30, 200, 30)
    pdf.ln(10)
    
    # Add menu content
    pdf.set_font('Arial', '', 12)
    
    if isinstance(menu, str):
        try:
            menu = clean_text(menu)
            menu_dict = json.loads(menu)
            for category, items in menu_dict.items():
                item = item.replace('•', '*')
                pdf.set_font('Arial', 'B', 14)
                pdf.cell(0, 10, category, 0, 1)
                pdf.set_font('Arial', '', 12)
                
                if isinstance(items, list):
                    for item in items:
                        pdf.cell(0, 8, f"• {item}", 0, 1)
                else:
                    pdf.multi_cell(0, 8, items)
                pdf.ln(5)
        except (json.JSONDecodeError, TypeError):
            # If it's not valid JSON, treat as plain text
            # Try to identify sections
            sections = re.split(r'\n\s*\n|\n(?=[A-Z][a-z]+:)', menu)
            for section in sections:
                if ':' in section:
                    parts = section.split(':', 1)
                    pdf.set_font('Arial', 'B', 14)
                    pdf.cell(0, 10, parts[0].strip(), 0, 1)
                    pdf.set_font('Arial', '', 12)
                    
                    items = parts[1].strip().split('\n')
                    for item in items:
                        if item.strip():
                            pdf.cell(0, 8, f"• {item.strip()}", 0, 1)
                else:
                    pdf.multi_cell(0, 8, section)
                pdf.ln(5)
    else:
        pdf.multi_cell(0, 10, str(menu))
    
    # Add footer
    pdf.set_y(-30)
    pdf.set_font('Arial', 'I', 8)
    pdf.cell(0, 10, "Generated by Master Chef AI - Your Personal Menu Designer", 0, 0, 'C')
    return pdf.output(dest='S').encode('latin1')
